apiVersion: apps/v1
kind: Deployment
metadata:
  name: buoeng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buoeng
  template:
    metadata:
      labels:
        app: buoeng
    spec:
      containers:
      - image: okteto.dev/buoeng:latest
        name: buoeng
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d722b9e3-87bf-40f2-a493-2646f9ca131c"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "d722b9e3-87bf-40f2-a493-2646f9ca131c"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/v2link"
